# Define paths
save_dir: /disk/xray0/tl3/project-nested-diffusion/proxnest/dev/tmp_storage/
input_data_dir: /disk/xray0/tl3/project-nested-diffusion/proxnest/data/

# Experiment name
experiment: diffnest_blur_64_
run_name: blur_long_run_3_

# Logging
wandb_vis: True
wandb_vis_imgs: True
wandb_vis_imgs_freq: 5
wandb_log_evidence_freq: 5

# Data
img_size: 64
sigma: None
dtype: uint
# dtype can be uint (0 to 255) or float
ISNR: 20

# Inverse problem params
blur_kernel_size: 3


# options - Nested sampling alg
samplesL: 1000
samplesD: 20000
tol: 1e-10
max_iter: 1000
verbose: True
# samplesL: Number of live samples
# samplesD: Number of discarded samples 
# tol: Convergence tolerance of algorithm (L2 Ball projection alg)
# max_iter: Maximum number of iterations (L2 Ball projection alg)
# verbose: Verbosity


# Diffusion params
model_type: imagenet
in_channels: 3
out_channels: 3
diffusion_steps: 100
lambda_: 7.0
zeta: 0.3
noise_init: True

# model_type: Type of pretrained model. Options are 'imagenet' or 'ffhq'
# in_channels: Channels in the input Tensor.
# out_channels: Channels in the output Tensor.
# Noise standard deviation of degraded image
# diffusion_steps: Maximum number of iterations of the DiffPIR algorithm
# lambda_: Regularisation parameter
# zeta: DiffPIR parameter controling the diffusion

